services:
  - type: web
    name: unirec-backend
    env: python
    buildCommand: "bash build.sh"
    startCommand: "cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
